-- =================================================================
-- PHẦN 1: CÁC BẢNG DANH MỤC & THÔNG SỐ (TẠO TRƯỚC)
-- =================================================================

CREATE TABLE LOAI_SP (
    MALOAI VARCHAR(20) PRIMARY KEY NOT NULL,
    TENLOAI VARCHAR(100) NOT NULL,
    MOTA TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE THUONGHIEU (
    MATHUONGHIEU VARCHAR(20) PRIMARY KEY NOT NULL,
    TENTHUONGHIEU VARCHAR(100) NOT NULL,
    QUOCGIA VARCHAR(100),
    MOTA TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE THONGSO_DUONGKINH(
    MADK VARCHAR(10) PRIMARY KEY NOT NULL,
    MOTA TEXT,
    CHISO TEXT,
    DONVIDO TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE THONGSO_CHIEUDAIDAY(
    MADD VARCHAR(10) PRIMARY KEY NOT NULL,
    MOTA TEXT,
    CHISO TEXT,
    DONVIDO TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE THONGSO_DODAY(
    MADDY VARCHAR(10) PRIMARY KEY NOT NULL,
    MOTA TEXT,
    CHISO TEXT,
    DONVIDO TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE THONGSO_CHIEURONGDAY(
    MCRD VARCHAR(10) PRIMARY KEY NOT NULL,
    MOTA TEXT,
    CHISO TEXT,
    DONVIDO TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE THONGSO_KHOILUONG(
    MKL VARCHAR(10) PRIMARY KEY NOT NULL,
    MOTA TEXT,
    CHISO TEXT,
    DONVIDO TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CONGNGHE_CHONGNUOC(
    MCN VARCHAR(10) PRIMARY KEY NOT NULL,
    TEN TEXT,
    MOTA TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MAUSAC(
    MMS VARCHAR(10) PRIMARY KEY NOT NULL,
    TENMAU TEXT,
    MOTA TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CACCHUCNANG(
    MCNANG VARCHAR(10) PRIMARY KEY NOT NULL,
    TENCHUCNANG TEXT,
    MOTA TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =================================================================
-- PHẦN 2: BẢNG SẢN PHẨM & KHUYẾN MÃI (CORE)
-- =================================================================

-- 2.1 Bảng Sản phẩm
CREATE TABLE SANPHAM (
    MASP VARCHAR(20) PRIMARY KEY NOT NULL,
    TENSP VARCHAR(200) NOT NULL,
    MATHUONGHIEU VARCHAR(20),
    MALOAI VARCHAR(20),
    GIABAN DECIMAL(15,0),
    GIANHAP DECIMAL(15,0),
    SOLUONGTON INT DEFAULT 0,
    HINHANHCHINH VARCHAR(255),
    CHITIETHINHANH VARCHAR(50), 

    -- Khóa ngoại thông số
    MADK VARCHAR(10),
    MADD VARCHAR(10),
    MADDY VARCHAR(10),
    MCRD VARCHAR(10),
    MKL VARCHAR(10),
    MCN VARCHAR(10),
    MMS VARCHAR(10),
    MCNANG VARCHAR(10),

    MOTA TEXT,
    TRANGTHAI TINYINT DEFAULT 1 COMMENT '1: Đang bán, 0: Ngừng kinh doanh',
    
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    NGAYSUA DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_SP_TH FOREIGN KEY (MATHUONGHIEU) REFERENCES THUONGHIEU(MATHUONGHIEU),
    CONSTRAINT FK_SP_LOAI FOREIGN KEY (MALOAI) REFERENCES LOAI_SP(MALOAI),
    CONSTRAINT FK_SP_DK FOREIGN KEY (MADK) REFERENCES THONGSO_DUONGKINH(MADK),
    CONSTRAINT FK_SP_DD FOREIGN KEY (MADD) REFERENCES THONGSO_CHIEUDAIDAY(MADD),
    CONSTRAINT FK_SP_DDY FOREIGN KEY (MADDY) REFERENCES THONGSO_DODAY(MADDY),
    CONSTRAINT FK_SP_CRD FOREIGN KEY (MCRD) REFERENCES THONGSO_CHIEURONGDAY(MCRD),
    CONSTRAINT FK_SP_KL FOREIGN KEY (MKL) REFERENCES THONGSO_KHOILUONG(MKL),
    CONSTRAINT FK_SP_CN FOREIGN KEY (MCN) REFERENCES CONGNGHE_CHONGNUOC(MCN),
    CONSTRAINT FK_SP_MS FOREIGN KEY (MMS) REFERENCES MAUSAC(MMS),
    CONSTRAINT FK_SP_CNANG FOREIGN KEY (MCNANG) REFERENCES CACCHUCNANG(MCNANG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.2 Bảng Chương trình Khuyến mãi
CREATE TABLE KHUYENMAI (
    MAKM VARCHAR(20) PRIMARY KEY NOT NULL,
    TENKM VARCHAR(200) NOT NULL,
    MA_CODE VARCHAR(20) UNIQUE COMMENT 'Mã Voucher (nếu có)',
    
    LOAIKM ENUM('PHAN_TRAM', 'TIEN_MAT') DEFAULT 'PHAN_TRAM', 
    GIATRI DECIMAL(15,0) NOT NULL,
    GIAM_TOI_DA DECIMAL(15,0),
    DON_TOI_THIEU DECIMAL(15,0) DEFAULT 0,
    
    NGAYBATDAU DATETIME NOT NULL,
    NGAYKETTHUC DATETIME NOT NULL,
    
    TRANGTHAI TINYINT DEFAULT 1 COMMENT '1: Active, 0: Inactive',
    SOLUONG_MA INT DEFAULT 0,
    
    MOTA TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.3 Bảng Trung gian: Sản phẩm áp dụng khuyến mãi (Flash Sale)
CREATE TABLE KHUYENMAI_SANPHAM (
    MAKM VARCHAR(20) NOT NULL,
    MASP VARCHAR(20) NOT NULL,
    PRIMARY KEY (MAKM, MASP),
    CONSTRAINT FK_KMSP_KM FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM),
    CONSTRAINT FK_KMSP_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =================================================================
-- PHẦN 3: QUẢN LÝ NHÂN SỰ
-- =================================================================

CREATE TABLE CHUCVU (
    MACV VARCHAR(10) PRIMARY KEY NOT NULL,
    TENCV VARCHAR(50) NOT NULL,
    QUYENHAN TEXT,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY NOT NULL,
    MACV VARCHAR(10) NOT NULL,
    HO VARCHAR(50) NOT NULL,
    TEN VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARCHAR(255) NOT NULL,
    SDT VARCHAR(15),
    DIACHI TEXT,
    NGAYVAOLAM DATE,
    TRANGTHAI TINYINT DEFAULT 1,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NV_CV FOREIGN KEY (MACV) REFERENCES CHUCVU(MACV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CALAMVIEC (
    MACA VARCHAR(10) PRIMARY KEY NOT NULL,
    TENCA VARCHAR(50) NOT NULL,
    GIOBATDAU TIME NOT NULL,
    GIOKETTHUC TIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE LICHLAMVIEC (
    MALICH INT AUTO_INCREMENT PRIMARY KEY,
    MANV VARCHAR(20) NOT NULL,
    MACA VARCHAR(10) NOT NULL,
    NGAYLAM DATE NOT NULL,
    GHICHU TEXT,
    TRANGTHAI ENUM('DA_PHAN_CONG', 'DA_LAM', 'VANG_MAT') DEFAULT 'DA_PHAN_CONG',
    CONSTRAINT FK_LICH_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_LICH_CA FOREIGN KEY (MACA) REFERENCES CALAMVIEC(MACA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =================================================================
-- PHẦN 4: QUẢN LÝ NHẬP HÀNG (SUPPLY CHAIN)
-- =================================================================

CREATE TABLE NHACUNGCAP (
    MANCC VARCHAR(20) PRIMARY KEY NOT NULL,
    TENNCC VARCHAR(100) NOT NULL,
    DIACHI TEXT,
    SDT VARCHAR(15),
    EMAIL VARCHAR(100),
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PHIEUNHAP (
    MAPN VARCHAR(20) PRIMARY KEY NOT NULL,
    MANV VARCHAR(20) NOT NULL,
    MANCC VARCHAR(20) NOT NULL,
    TONGTIEN DECIMAL(15,0) DEFAULT 0,
    GHICHU TEXT,
    NGAYNHAP DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PN_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CHITIETPHIEUNHAP (
    MAPN VARCHAR(20) NOT NULL,
    MASP VARCHAR(20) NOT NULL,
    SOLUONG INT NOT NULL CHECK (SOLUONG > 0),
    GIANHAP DECIMAL(15,0) NOT NULL,
    THANHTIEN DECIMAL(15,0) NOT NULL,
    PRIMARY KEY (MAPN, MASP),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),
    CONSTRAINT FK_CTPN_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =================================================================
-- PHẦN 5: KHÁCH HÀNG & GIỎ HÀNG
-- =================================================================

CREATE TABLE KHACHHANG (
    MAKH INT AUTO_INCREMENT PRIMARY KEY,
    HOTEN VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SDT VARCHAR(15),
    MATKHAU VARCHAR(255),
    DIACHI TEXT,
    TRANGTHAI TINYINT DEFAULT 1,
    NGAYTAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    NGAYSUA DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE GIOHANG (
    MAKH INT NOT NULL,
    MASP VARCHAR(20) NOT NULL,
    SOLUONG INT DEFAULT 1,
    NGAYTHEM DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MAKH, MASP),
    CONSTRAINT FK_GH_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_GH_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =================================================================
-- PHẦN 6: BÁN HÀNG & ĐƠN HÀNG (SALES)
-- =================================================================

CREATE TABLE DONHANG (
    MADH VARCHAR(20) PRIMARY KEY NOT NULL,
    MAKH INT NOT NULL,
    MANV_DUYET VARCHAR(20),
    
    -- Áp dụng mã khuyến mãi (Nếu có)
    MAKM VARCHAR(20) NULL, 
    
    -- Thông tin nhận hàng
    TEN_NGUOINHAN VARCHAR(100) NOT NULL,
    SDT_NGUOINHAN VARCHAR(15) NOT NULL,
    DIACHI_GIAOHANG TEXT NOT NULL,
    
    -- Tiền tệ
    TONGTIENHANG DECIMAL(15,0) DEFAULT 0,
    PHIVANCHUYEN DECIMAL(15,0) DEFAULT 0,
    GIAMGIA DECIMAL(15,0) DEFAULT 0,
    TONGTHANHTOAN DECIMAL(15,0) DEFAULT 0,
    
    -- Thanh toán & Trạng thái
    PT_THANHTOAN VARCHAR(50) DEFAULT 'COD',
    TRANGTHAI_THANHTOAN TINYINT DEFAULT 0, -- 0: Chưa, 1: Rồi
    
    -- Status Đơn hàng: 1:ChoXN, 2:DaXN, 3:DangGiao, 4:ThanhCong, 5:Huy, 6:TraHang
    TRANGTHAI_DONHANG INT DEFAULT 1, 
    
    -- Xử lý hủy
    YEU_CAU_HUY TINYINT DEFAULT 0, 
    LYDO_HUY TEXT,
    
    GHICHU TEXT,
    NGAYDAT DATETIME DEFAULT CURRENT_TIMESTAMP,
    NGAYCAPNHAT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_DH_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_DH_NV FOREIGN KEY (MANV_DUYET) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_DH_KM FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CHITIETDONHANG (
    MADH VARCHAR(20) NOT NULL,
    MASP VARCHAR(20) NOT NULL,
    SOLUONG INT NOT NULL,
    DONGIA DECIMAL(15,0) NOT NULL,
    THANHTIEN DECIMAL(15,0) NOT NULL,
    PRIMARY KEY (MADH, MASP),
    CONSTRAINT FK_CTDH_DH FOREIGN KEY (MADH) REFERENCES DONHANG(MADH),
    CONSTRAINT FK_CTDH_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =================================================================
-- PHẦN 7: GIAO VẬN (LOGISTICS)
-- =================================================================

CREATE TABLE DONVIVANCHUYEN (
    MADVVC VARCHAR(10) PRIMARY KEY NOT NULL,
    TENDVVC VARCHAR(50) NOT NULL,
    HOTLINE VARCHAR(20),
    DIACHI TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE GIAOHANG (
    MAGIAOVAN VARCHAR(20) PRIMARY KEY NOT NULL,
    MADH VARCHAR(20) NOT NULL,
    MADVVC VARCHAR(10) NOT NULL,
    
    SHIPPER_TEN VARCHAR(50),
    SHIPPER_SDT VARCHAR(15),
    
    TRANGTHAI_GIAO VARCHAR(20) DEFAULT 'DANG_LAY_HANG',
    MOTA_SUCO TEXT,
    
    NGAYGIAO DATETIME DEFAULT CURRENT_TIMESTAMP, 
    NGAYHOANTAT DATETIME,
    
    CONSTRAINT FK_GIAO_DH FOREIGN KEY (MADH) REFERENCES DONHANG(MADH),
    CONSTRAINT FK_GIAO_DVVC FOREIGN KEY (MADVVC) REFERENCES DONVIVANCHUYEN(MADVVC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;